name: Deploy GitHub Pages

# 觸發條件：在推送到 main 分支時執行
on:
  push:
    branches:
      - main

# 設置全局權限
permissions:
  contents: write  # 授予寫入儲存庫內容的權限

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代碼
      - name: Checkout
        uses: actions/checkout@v4  # 升級到最新版本

      # 設置 Node.js 環境
      - name: Setup Node.js environment
        uses: actions/setup-node@v4  # 升級到最新版本
        with:
          node-version: "18.20.3"
          cache: "yarn"  # 啟用 Yarn 緩存
          cache-dependency-path: documents/yarn.lock  # 指定 Yarn 鎖定文件路徑

      # 安裝 Yarn
      - name: Install Yarn
        run: npm install -g yarn

      # 安裝依賴
      - name: Install dependencies
        run: cd documents && yarn install

      # 生成靜態文件
      - name: Build
        run: cd documents && yarn docs:build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages  # 修正為 target_branch
          build_dir: documents/docs/.vitepress/dist
          keep_history: false
          allow_empty_commit: true
          jekyll: true
          dry_run: false
          verbose: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
